# Generated by Django 2.1.2 on 2019-02-04 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('code', models.TextField()),
                ('body', models.TextField()),
                ('output', models.ImageField(upload_to='images/')),
                ('url', models.TextField()),
                ('downloads', models.IntegerField(default=0)),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
